909:
  video_url:
  artist_name: Bing Bin 宾冰
  bio_chin: >
    公交车与声音/音乐最直接的联系是广播节目/流行音乐电台或电视节目。
    这组声音作品共有三个音频，随机播放，每个音频基于音乐电台模式，
    次序放入变形后的流行歌曲，这些歌曲均由网络下载（未付费）。
    每个音频中另一音轨的内容则来自米兰·昆德拉的小说《生命中不能承受之轻》
    关于“媚俗”的讨论。此外，由于个人经历，这组作品亦通过一种轻盈的方式表达对声音/音乐的不确定性、
    甚至不可靠性及数字科技所带来的困惑。
    <br>宾冰生于湖南，现居北京，视觉艺术及文字工作者。
  bio_eng: >
    The most direct link between bus and sound/music is broadcasting/music radio or TV programme playing pop songs. 
    There are three pieces of work in total, each of which plays at random. Each piece is based on a music radio mode, 
    namely a mix with several deformed pop songs. All the songs come from illegal downloading. The content of another track in each 
    piece is some writings on Kitsch from Milan Kundera's novel The Unbearable Lightness of Being. 
    In addition, because of personal experience, her work, in a lightness way, is an expression on confusion about digital technology and 
    the uncertainty, even unreliability of sound/music.
    <br>Bing Bin was born in Hunan Province. Currently working in visual arts, writing and translation in Beijing.

731:
  video_url: 
  artist_name: Simon Frank
  bio_chin: <a href="www.simonfrank.bandcamp.com" target="_new">Simon Frank's Bandcamp</a>
  bio_eng: >
    Simon Frank is a geographically challenged graduate students and musician currently based in London. 
    He mostly tries to push simple ideas past their limit. Simon is one half of the duo Hot & Cold

674:
  video_url:
  artist_name: Parallel Pyres (Joshua Frank)
  bio_chin:
  bio_eng: >
    Parallel Pyres is the transnational blues solo project of musician and filmmaker Joshua Frank. 
    It materialized between Beijing, Montreal, Taipei and New York.

918:
  video_url:
  artist_name: thruoutin (Brad Seippel)
  bio_chin: >
    来自美国的电子音乐家与音乐制作人thruoutin，在中国成立了5年。多元化的音乐风格，把奇怪的温情电子和中国民乐音乐结合在一起。
    你可以听到多种艺术创作思维在他的音乐里，尤其是对大自然的采样和物理电子声音的钟爱。并曾在加拿大.台湾.韩国.
    中国和美国周边的几个城市都有过精彩的演出，除了他个人独立发行的唱片外，
    他与多家唱片公司都有过合作关系。比如说：京味儿（北京）Huashan (上海), 87非87 (北京), and Aud-Art （匹兹堡）
  bio_eng: >
    American born electronic producer and multi-instrumentalist, thruoutin, has been based in China since 2009.  
    His work varies from project to project, but often revolves around the combining of different genres 
    and with a focus on organic and digital sounds.  He has brought his music to Canada, Taiwan, Korea and 
    various cities in the US and throughout mainland China.  Besides self-releases, thruoutin has also been 
    featured on such labels as Jingweir (Beijing), Huashan (Shanghai), 87Fei87 (Beijing), and Aud-Art (Pittsburg).
113:
  video_url:
  artist_name: Charm (Josh Feola)
  bio_chin: > 
    Charm是一个长期的表演和录音项目，包括田野录音，"拾得"文化声音, 消衰反馈／噪音／长音拼贴。
    Charm是居住在北京的音乐人、作家、策划人Josh Feola的个人项目。Feola活跃于北京地下实验音乐圈，
    他所主持建立的旁边儿 (<a href="pangbianr.com" target="_blank">pangbianr.com</a>）自2010年以来成为一个重要的地下音乐文化交流与传播的网络平台。
  bio_eng: >
    Charm is the solo project of Josh Feola, a Beijing-based musician, writer, and event curator. 
    Feola has been active in Beijing's underground experimental music scene since 2010 via his organizational 
    platform Pangbianr (<a href="pangbianr.com" target="_blank">pangbianr.com</a>). He's currently the music & arts editor of SmartBeijing.com, 
    co-founder of the Sinotronics record label (<a href="http://sinotronics.org" target="_new">sinotronics.org</a>), founding member of the Sino-Indian Music Alliance (SIMA), 
    and drummer of Beijing rock band SUBS. Charm is an ongoing performance and recording project incorporating field recordings, 
    "found" cultural sounds, and decaying feedback/noise/drone collages.
109:
  video_url:
  artist_name: Peter Cusack
  bio_chin: >
    Peter Cusack is a field recordist, musician and researcher with a special interest in the acoustic environment. 
    He is a member of CRiSAP (Creative Research into Sound Art Practice) at LCC, UAL.
    <br>In 1998 he initiated the long running 'Favourite Sounds Project', to discover how people interact 
    with everyday sound in the places where they live, carried out initially in London and subsequently in Beijing, 
    Birmingham, Manchester, Prague and Berlin. His project ‘Sounds From Dangerous Places’ (described as sonic journalism) investigates the soundscapes of sites of major environmental damage such as the Caspian oil fields and the Chernobyl exclusion zone.
    <br>He produced 'Vermilion Sounds' - the environmental sound program - for ResonanceFM Radio, 
    London and, during 2011/12, was DAAD artist-in-residence in Berlin, where he instigated ‘Berlin Sonic Places’ a 
    wide-ranging collaborative project that examines the relationship between urban soundscapes and city development.
    <br>CDs include Your Favourite London Sounds (Resonance); Baikal Ice (ReR PC2); 
    Favourite Beijing Sounds (KwanYin 022); Sound from Dangerous Places (ReR PC3&4); 
    Favourite Berlin Sounds (ReR PC5).
  bio_eng: 

586:
  video_url:
  artist_name: 
  bio_chin:
  
